* doc-gnome/C/mkhtml: Support $JADE. Check that $DSL exists. By default exit after the first error in jade.

diff --git a/doc-gnome/C/mkhtml b/doc-gnome/C/mkhtml
--- a/doc-gnome/C/mkhtml
+++ b/doc-gnome/C/mkhtml
@@ -6,7 +6,8 @@
 
 # Adjustable parts.
 : ${DSL=/usr/share/sgml/docbook/utils-0.6/docbook-utils.dsl}
-: ${JADEFLAGS=}
+: ${JADE=jade}
+: ${JADEFLAGS=-E 1}
 
 # Exit on errors.
 set -e
@@ -38,13 +39,16 @@ for signal in 0 1 2 13 15; do
 	exit $status' $signal
 done
 
+# Make sure $DSL exists. TODO: search in all known locations here.
+test -f "$DSL" || { echo "$DSL not found"; exit 1; }
+
 # Complicated bootstrap process - create empty genindex.sgml first,
 # then generate it and then generate html files again.
 echo >genindex.sgml
 
 # First pass
 echo "First pass"
-jade $JADEFLAGS -t sgml -i html -d "$DSL#html" -V html-index=1 gmc.sgml
+$JADE $JADEFLAGS -t sgml -i html -d "$DSL#html" -V html-index=1 gmc.sgml
 
 # collateindex.pl may not have /usr/bin/perl on the first line.
 echo "Generating index"
@@ -53,5 +57,5 @@ rm -f HTML.index
 
 # Second pass with the right genindex.sgml
 echo "Second pass"
-jade $JADEFLAGS -t sgml -i html -d "$DSL#html" gmc.sgml
+$JADE $JADEFLAGS -t sgml -i html -d "$DSL#html" gmc.sgml
 
